//ui logic
$(document).ready(function(){
  $("#form1").submit(function(event){
  event.preventDefault();

  var userName = $("#username").val();

  var userGuess = $("#user-guess").val();

  var userScore = 5;








  //business logic

  function User(name, guess, score){
    this.name = name;
    this.guess = guess;
    this.score = score;
  }

  var newUser = new User(userName, userGuess, userScore);

  var words = ["Superman", "Spiderman", "Nathan Drake",
               "Steve Jobs", "Batman", "Iron Man", "Antman",
               "Hellboy", "Luke Skywalker", "Ben Kenobi",
               "Darth Vader", "Spartan 117"];

  var randomNum = Math.floor(Math.random() * words.length);

  var randomWord = words[randomNum];

  console.log(randomWord);

  let guessChecker = function(){

    if(newUser.guess === randomWord[0] || randomWord[0].toLowerCase()){
      newUser.guess = newUser.guess.toUpperCase();
      console.log(newUser.guess);
    }

    for(i=0;i<randomWord.length; i++){
      //console.log(randomWord[i]);
    if(randomWord[i] === userGuess){
      console.log(userGuess);
    	}continue;
  	}
  }

  //end business logic





  console.log(newUser);

  guessChecker();

  });
});












/*

Working version:

1) + random word is generated by the computer, by passing randomNumber into words[]

2) + user can guess a letter, which is stored into a variable

3) + guessChecker() will loop through all letters of randomWord to verify a match or not

3) + if guessChecker() finds a match that letter will be logged by the console

4) - if the user's guess does not match any of the letters in the randomly generated word,
  then one point will be subtracted from the score and
  and that letter should be displayed in the wrong guesses display field
5) - The score will begin at 5. When the score reaches 0, and not all letters have been matched, the player loses
6) - If the score is > 0 by and all letters of the word have been filled in, then the user will window
7) - the user will need the ablity to quit and any moment they want

*/
