//ui logic
$(document).ready(function(){
  $("#form1").submit(function(event){
  event.preventDefault();

  let userName = $("#username").val();
  let userGuess = $("#user-guess").val();
  let userScore = 5;





  //business logic

  function User(name, guess, score){
    this.name = name;
    this.guess = guess;
    this.score = score;
  }

  let newUser = new User(userName, userGuess, userScore);

  let words = ["Superman", "Spiderman", "Sinderella",
               "Stacon", "Satman", "Sintin", "Saruman",
               "Sellboy", "Soda", "Shewbacca",
               "Sandalf", "Sortana"];

  var randomNum = Math.floor(Math.random() * words.length);

  var randomWord = words[randomNum];

  console.log(randomWord);

  let guessChecker = function(){

    let nUG = newUser.guess;

    if(nUG.toUpperCase() === randomWord[0]){
      nUG = nUG.toUpperCase();
      console.log(nUG);
    }

    for(i=0;i<randomWord.length; i++){
      if(randomWord[i] === nUG){
        console.log(nUG);
        break;
      }else{
        newUser.score --
        console.log(newUser.score);
        break;
      }
    }

  }

  //end business logic





  console.log(newUser);

  while(newUser.score != 0){ //may not work
    guessChecker();
  }

  });
});












/*

Working version:

1) + random word is generated by the computer, by passing randomNumber into words[]

2) + user can guess a letter, which is stored into a variable

3) + guessChecker() will loop through all letters of randomWord to verify a match or not

3) + if guessChecker() finds a match that letter will be logged by the console

4) - if the user's guess does not match any of the letters in the randomly generated word,
  then one point will be subtracted from the score and
  and that letter should be displayed in the wrong guesses display field
5) - The score will begin at 5. When the score reaches 0, and not all letters have been matched, the player loses
6) - If the score is > 0 by and all letters of the word have been filled in, then the user will window
7) - the user will need the ablity to quit and any moment they want

*/
